services:
  postgres:
    extends:
      service: postgres
      file: services.yaml
    container_name: postgres-test-container
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - target: 5432