server:
  port: ${SERVER_PORT}

spring:
  application:
    name: management-service
  docker:
    compose:
      file: docker-compose-dev.yaml

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
