server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: management-service
  config:
    import: optional:file:.env[.properties]
  docker:
    compose:
      file: docker-compose-dev.yaml

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true