server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: management-service
  config:
    import: optional:file:.env[.properties]
  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

debezium:
  enabled: true
  connector-name: postgres-connector
  connect-url: http://localhost:8083
  config:
    topic:
      prefix: "management-service"
    database:
      hostname: postgres
      port: ${DB_PORT}
      user: debezium
      password: DEBEZIUM_PASSWORD
      dbname: ${DB_NAME}
    slot: debezium_slot
    publication: hotel_pub
    table-include-list: "public.hotel,public.location,public.amenity,public.room_type,public.hotel_room,public.hotel_amenities,public.hotel_photo"

storage:
  s3:
    endpoint: https://s3.cloud.ru
    region: ru-central-1
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    bucket: dev-bucket-hbs
    path:
      delim: /
    url-expiration-seconds: 900


management:
  endpoint:
    env:
      show-values: always
  endpoints:
    web:
      exposure:
        include: env

logging:
  level:
    com.hbs.managamentservice: DEBUG