-- liquibase formatted sql

-- changeset kanaoki:1748006867363-1
CREATE TABLE location (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, country VARCHAR(100) NOT NULL, city VARCHAR(150) NOT NULL, street VARCHAR(255) NOT NULL, building VARCHAR(25) NOT NULL, zip_code VARCHAR(25) NOT NULL, CONSTRAINT pk_location PRIMARY KEY (id));

-- changeset kanaoki:1748006867363-2
ALTER TABLE hotel ADD location_id BIGINT;

-- changeset kanaoki:1748006867363-3
ALTER TABLE hotel ADD CONSTRAINT FK_HOTEL_ON_LOCATION FOREIGN KEY (location_id) REFERENCES location (id);

