-- liquibase formatted sql

-- changeset kanaoki:1748011358435-1
CREATE TABLE amenity (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, icon OID NOT NULL, CONSTRAINT pk_amenity PRIMARY KEY (id));

