-- liquibase formatted sql

-- changeset aqua:1748034899592-1
CREATE TABLE room_type (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, bed_type VARCHAR(255) NOT NULL, area FLOAT NOT NULL, max_guests SMALLINT NOT NULL, CONSTRAINT pk_roomtype PRIMARY KEY (id));

