-- liquibase formatted sql

-- changeset aqua:1748112171818-34
ALTER TABLE hotel_room DROP CONSTRAINT fk_hotelroom_on_hotel;

-- changeset aqua:1748112171818-35
ALTER TABLE hotel_room DROP CONSTRAINT fk_hotelroom_on_room_type;

-- changeset aqua:1748112171818-8
CREATE TABLE hotel_amenities (amenities_id BIGINT NOT NULL, hotel_id BIGINT NOT NULL, CONSTRAINT pk_hotel_amenities PRIMARY KEY (amenities_id, hotel_id));

-- changeset aqua:1748112171818-9
CREATE TABLE hotel_photo (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url VARCHAR(1024) NOT NULL, hotel_id BIGINT, created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, CONSTRAINT pk_hotelphoto PRIMARY KEY (id));

-- changeset aqua:1748112171818-10
ALTER TABLE hotel ADD created_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE hotel ADD description OID;
ALTER TABLE hotel ADD is_active BOOLEAN;
ALTER TABLE hotel ADD name VARCHAR(150);
ALTER TABLE hotel ADD stars INTEGER;
ALTER TABLE hotel ADD status VARCHAR(255);
ALTER TABLE hotel ADD updated_at TIMESTAMP WITHOUT TIME ZONE;

-- changeset aqua:1748112171818-11
ALTER TABLE hotel ALTER COLUMN  created_at SET NOT NULL;

-- changeset aqua:1748112171818-13
ALTER TABLE hotel ALTER COLUMN  description SET NOT NULL;

-- changeset aqua:1748112171818-14
ALTER TABLE hotel_room ADD hotel_id BIGINT;
ALTER TABLE hotel_room ADD room_type_id BIGINT;

-- changeset aqua:1748112171818-17
ALTER TABLE hotel ALTER COLUMN  name SET NOT NULL;

-- changeset aqua:1748112171818-19
ALTER TABLE hotel_room ALTER COLUMN  room_type_id SET NOT NULL;

-- changeset aqua:1748112171818-21
ALTER TABLE hotel ALTER COLUMN  stars SET NOT NULL;

-- changeset aqua:1748112171818-23
ALTER TABLE hotel ALTER COLUMN  status SET NOT NULL;

-- changeset aqua:1748112171818-25
ALTER TABLE hotel ALTER COLUMN  updated_at SET NOT NULL;

-- changeset aqua:1748112171818-26
ALTER TABLE hotel ADD CONSTRAINT uc_hotel_location UNIQUE (location_id);

-- changeset aqua:1748112171818-27
ALTER TABLE hotel_photo ADD CONSTRAINT uc_hotelphoto_url UNIQUE (url);

-- changeset aqua:1748112171818-28
ALTER TABLE hotel_room ADD CONSTRAINT uc_hotelroom_roomtype UNIQUE (room_type_id);

-- changeset aqua:1748112171818-29
ALTER TABLE hotel_photo ADD CONSTRAINT FK_HOTELPHOTO_ON_HOTEL FOREIGN KEY (hotel_id) REFERENCES hotel (id);

-- changeset aqua:1748112171818-30
ALTER TABLE hotel_room ADD CONSTRAINT FK_HOTELROOM_ON_HOTEL FOREIGN KEY (hotel_id) REFERENCES hotel (id);

-- changeset aqua:1748112171818-31
ALTER TABLE hotel_room ADD CONSTRAINT FK_HOTELROOM_ON_ROOMTYPE FOREIGN KEY (room_type_id) REFERENCES room_type (id);

-- changeset aqua:1748112171818-32
ALTER TABLE hotel_amenities ADD CONSTRAINT fk_hotame_on_amenity FOREIGN KEY (amenities_id) REFERENCES amenity (id);

-- changeset aqua:1748112171818-33
ALTER TABLE hotel_amenities ADD CONSTRAINT fk_hotame_on_hotel FOREIGN KEY (hotel_id) REFERENCES hotel (id);

-- changeset aqua:1748112171818-36
ALTER TABLE hotel_room DROP COLUMN hotel;
ALTER TABLE hotel_room DROP COLUMN room_type;
ALTER TABLE hotel_room DROP COLUMN floor;

-- changeset aqua:1748112171818-1
ALTER TABLE room_type DROP COLUMN description;
ALTER TABLE room_type DROP COLUMN max_guests;

-- changeset aqua:1748112171818-2
ALTER TABLE room_type ADD description OID NOT NULL;

-- changeset aqua:1748112171818-4
ALTER TABLE hotel_room ADD floor INTEGER NOT NULL;

-- changeset aqua:1748112171818-6
ALTER TABLE room_type ADD max_guests INTEGER NOT NULL;

-- changeset aqua:1748112171818-7
ALTER TABLE hotel_room ALTER COLUMN price_per_night TYPE DECIMAL USING (price_per_night::DECIMAL);

