name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - feature/*
  pull_request:
    branches:
      - master
      - feature/*

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      build_dir: ${{ steps.build.outputs.build_dir }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assemble project
        run: ./gradlew clean assemble --no-daemon --info

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/libs/*.jar
          retention-days: 7

  unit-tests:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test --tests "*unit.*" --no-daemon

      - name: Generate JaCoCo Report
        run: ./gradlew jacocoTestReport --no-daemon

      - name: Upload JaCoCo Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: |
            build/reports/jacoco/test/html/
            build/reports/jacoco/test/jacocoTestReport.xml
          retention-days: 7

  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run integration tests
        run: ./gradlew test --tests "*integration.*" --no-daemon

  sonar:
    needs: [unit-tests, integration-tests]
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: SonarQube Scan
        uses: sonarSource/sonarcloud-github-action@master
        with:
          args: -Dproject.settings=./sonar-project.properties
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}